# Generated by Django 5.1.4 on 2025-01-14 22:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/default_avatar.webp', storage=users.models.OverwriteStorage, upload_to=users.models.avatar_path),
        ),
    ]
