# Generated by Django 5.1.4 on 2025-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifytoken',
            name='duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
