# Generated by Django 5.1.4 on 2025-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverifytoken_duplicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
